// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejqcvhvbroabygbtgjjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcWN2aHZicm9hYnlnYnRnampuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNTA1MDEsImV4cCI6MjA4NTgyNjUwMX0.PTnc-XvrrkwpfQLTk3wwn1eG4h9nj8hGAdlFBbfJ4Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});